version: '3.8'

services:
  app:
    build: .
    container_name: fxql-parser
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db.example.com
      DB_PORT: 5432
      DB_DATABASE: fxql_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_SSL_MODE: true
    restart: always
